# Generated by Django 2.2.2 on 2019-07-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter7', '0002_auto_20190714_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=8),
        ),
    ]
