# Generated by Django 2.1.7 on 2019-05-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='stus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xm', models.CharField(max_length=8)),
                ('shets', models.ManyToManyField(to='faqs.shet')),
            ],
        ),
    ]
