# Generated by Django 2.2.2 on 2019-06-13 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0003_auto_20190610_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='stus3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xm', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=8)),
                ('stu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='faqs.stus3')),
            ],
        ),
    ]
