# Generated by Django 2.2.2 on 2019-06-14 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0004_cards_stus3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='stu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='faqs.stus3'),
        ),
    ]
