"""empty message

Revision ID: a6d1d0e39b95
Revises: 
Create Date: 2023-03-16 09:23:30.681258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d1d0e39b95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=8), nullable=True),
    sa.Column('user_pw', sa.String(length=12), nullable=True),
    sa.Column('user_name', sa.String(length=8), nullable=True),
    sa.Column('user_fullname', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_fullname'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_name'),
    sa.UniqueConstraint('user_pw')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
