"""empty message

Revision ID: 5bb644e7b3c6
Revises: 
Create Date: 2023-03-08 17:38:48.168935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5bb644e7b3c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('u_name', sa.String(length=8), nullable=True),
    sa.Column('u_pwd', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('u_name'),
    sa.UniqueConstraint('u_pwd')
    )
    op.drop_table('chin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chin',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('uname', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('info', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ranking', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_model')
    # ### end Alembic commands ###
