# Generated by Django 2.2.4 on 2019-10-29 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zy',
            fields=[
                ('zsdm', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('zymc', models.CharField(max_length=10)),
                ('cc', models.CharField(max_length=10)),
                ('sfbz', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='lq',
            fields=[
                ('zkzh', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('xm', models.CharField(max_length=10)),
                ('zy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zs.zy')),
            ],
        ),
    ]
