"""empty message

Revision ID: 78a0918575a4
Revises: 
Create Date: 2023-03-14 13:51:03.128177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a0918575a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('u_name', sa.String(length=8), nullable=True),
    sa.Column('u_pwd', sa.String(length=12), nullable=True),
    sa.Column('user_fullname', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('u_id', 'user_id'),
    sa.UniqueConstraint('u_name'),
    sa.UniqueConstraint('u_pwd'),
    sa.UniqueConstraint('user_fullname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_model')
    # ### end Alembic commands ###
