# Generated by Django 2.2.2 on 2019-07-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='用户名由英文字母、数字等字符组成', max_length=10, verbose_name='用户名')),
                ('password', models.CharField(help_text='登录密码为6-8位字符组成', max_length=6, verbose_name='密码')),
                ('email', models.CharField(help_text='有效电子邮件地址', max_length=30, verbose_name='Email')),
            ],
        ),
    ]
