# Generated by Django 2.2.2 on 2019-07-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uid',
            field=models.CharField(max_length=10),
        ),
    ]
