# Generated by Django 2.2.2 on 2019-08-02 01:29

from django.db import migrations, models
import userdiy.models


class Migration(migrations.Migration):

    dependencies = [
        ('userdiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='qq',
            field=models.CharField(max_length=11, validators=[userdiy.models.validate_qq]),
        ),
    ]
