# Generated by Django 2.2.2 on 2019-08-02 01:36

from django.db import migrations, models
import userdiy.models


class Migration(migrations.Migration):

    dependencies = [
        ('userdiy', '0002_auto_20190802_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=11, validators=[userdiy.models.validate_phone], verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='qq',
            field=models.CharField(max_length=11, validators=[userdiy.models.validate_qq], verbose_name='QQ号'),
        ),
    ]
